### ISSUE TITLE
Error running on compounds with symbolic allele

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/vip-inheritance-matcher#11]
## Reproduce
```
Execute /groups/umcg-gdio/tmp01/projects/modular_ngs_pipeline/2003_HLHS1_Diemen/v2.2.0/run0/run0.sh
```
## Actual
```
step 4/5 inheritance matching ...
Cannot find a variant for compound key '9_140772695_G_DEL'.
org.molgenis.vcf.inheritance.matcher.UnknownVariantException: Cannot find a variant for compound key '9_140772695_G_DEL'.
        at org.molgenis.vcf.inheritance.matcher.InheritanceMatcher.matchCompound(InheritanceMatcher.java:123)
        at org.molgenis.vcf.inheritance.matcher.InheritanceMatcher.matchInheritanceMode(InheritanceMatcher.java:102)
        at org.molgenis.vcf.inheritance.matcher.InheritanceMatcher.matchInheritance(InheritanceMatcher.java:85)
        at org.molgenis.vcf.inheritance.matcher.InheritanceMatcher.mapAndMatch(InheritanceMatcher.java:68)
        at org.molgenis.vcf.inheritance.matcher.AppCommandLineRunner.run(AppCommandLineRunner.java:79)
```

Symbolic allele `<DEL>` doesn't have angular brackets in the identifier 9_140772695_G_DEL resulting in the failure.

**Comment by dennishendriksen** [comment]
Genmod builds a variant identifier as follows: https://github.com/moonso/genmod/blob/3.7.3/genmod/vcf_tools/parse_variant.py
