### ISSUE TITLE
YL inheritance pattern causes unexpected enum exception

### ISSUE THREAD

**Issue by bartcharbon** [molgenis/vip-inheritance-matcher#52]
Unexpected enum constant 'YL' for type 'InheritanceMode'
org.molgenis.vcf.utils.UnexpectedEnumException: Unexpected enum constant 'YL' for type 'InheritanceMode'
	at org.molgenis.vcf.inheritance.matcher.InheritanceMatcher.isMatch(InheritanceMatcher.java:93)
	at org.molgenis.vcf.inheritance.matcher.InheritanceMatcher.lambda$matchGeneInheritance$0(InheritanceMatcher.java:57)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1728)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)

**Comment by bartcharbon** [comment]
fixed in https://github.com/molgenis/vip-inheritance-matcher/pull/51
